#define COMPONENT 3den
#include "\x\gw\addons\main\script_mod.hpp"

//#define DEBUG_ENABLED_3DEN

#ifdef DEBUG_ENABLED_3DEN
    #define DEBUG_MODE_FULL
#endif

#ifdef DEBUG_SETTINGS_3DEN
    #define DEBUG_SETTINGS DEBUG_SETTINGS_3DEN
#endif

#include "\x\gw\addons\main\script_macros.hpp"
#include "\a3\3DEN\UI\dikCodes.inc"

#define HIDEOBJECTFILTER ["BUILDING","BUNKER","BUSH","BUSSTOP","CHAPEL","CHURCH","CROSS","FENCE","FOREST BORDER","FOREST SQUARE","FOREST TRIANGLE","FOREST","FORTRESS","FOUNTAIN","FUELSTATION","HOSPITAL","HOUSE","LIGHTHOUSE","LINES","POWER""POWERSOLAR","POWERWAVE","POWERWIND","QUAY","RAILWAY","ROCK","ROCKS","RUIN","SHIPWRECK","SMALL TREE","STACK","TOURISM","TRANSMITTER","TREE","VIEW-TOWER","WALL","WATERTOWER","HIDE"]
